### ISSUE TITLE
Error: Cannot open sheet

### ISSUE THREAD

**Issue by TheMorningStarLucifer** [JPMeehan/prime-psionics#13]
When I create a power and try to open it I get this error:
<img width="271" alt="image" src="https://github.com/JPMeehan/prime-psionics/assets/137843163/b56fc044-10e5-457a-bf1b-b736cab2e83f">

**Comment by JPMeehan** [comment]
I should probably mark this module as incompatible with the Tidy5Esheet, it's clear tidy5e makes certain assumptions

**Comment by JPMeehan** [comment]
@TheMorningStarLucifer you can fix this yourself by configuring the default sheets in settings away from tidy5e's attempt.
