### ISSUE TITLE
[Feature Request] Make a variable flag for number of power points total consumed

### ISSUE THREAD

**Issue by GhostwheelX** [JPMeehan/prime-psionics#19]
The current `@item.consume` flag specifies the base number of psi points that a power consumes.

Would it be possible to create another variable for the _total_ number of PP consumed by a power? This would help a lot when setting up automation using [Dynamic Active Effects](https://gitlab.com/tposney/dae).

**Comment by JPMeehan** [comment]
There's a fundamental issue where the way 5e handles this is by creating a clone of the spell with the adjusted level; I can't pull that off in a hook.

**Comment by JPMeehan** [comment]
Handled in the new 2.0 update with the rework of 5e's scaling
