### ISSUE TITLE
[Feature Request] Allow psi points to show up on the flags of features

### ISSUE THREAD

**Issue by GhostwheelX** [JPMeehan/prime-psionics#20]
Currently, if you create a feature, you are unable to choose Psi Points from the flags list.

Would it be possible to allow Psi Points to be chosen there?
![image](https://github.com/JPMeehan/prime-psionics/assets/68725723/aeaf4a38-11bd-4076-9d71-442a1ad4b265)

**Comment by JPMeehan** [comment]
Currently blocked by https://github.com/foundryvtt/dnd5e/issues/2412

**Comment by JPMeehan** [comment]
This is handled by the new Psi Points consumption type
