### ISSUE TITLE
Tidy5e Sheet - prime-psionics.power.hbs is missing

### ISSUE THREAD

**Issue by Silvestrae** [JPMeehan/prime-psionics#23]
Console says it cannot open 'power' item sheets because \Data\systems\dnd5e\templates\items\prime-psionics.power.hbs is missing

**Comment by JPMeehan** [comment]
Please swap to the sheet provided by Prime Psionics using your game settings.

**Comment by Silvestrae** [comment]
![Screenshot_20231010_001542_TeamViewer](https://github.com/JPMeehan/prime-psionics/assets/55987580/81150347-0d65-40a1-9c59-e24d585e3ef8)

Thanks, I have explicitly set the sheet for a test 'power' item as the power.PowerSheet option and that sheet will now open.
However whenever I try to set the DEFAULT sheet of the power item to the power.Powersheet and press save, the config disappears but doesn't save and automatically reverts back to the Tidysheet as default.
Any ideas why it might not be saving as the default sheet? 
Console after saving config below. 

![Screenshot_20231010_002750_TeamViewer](https://github.com/JPMeehan/prime-psionics/assets/55987580/6f26ba19-2b68-48f8-aab6-fc143aebcef6)

**Comment by JPMeehan** [comment]
Looking into this I think it's just Tidy5e is poorly implemented and does not account for module subtypes. As that module is no longer maintained, this isn't too surprising but is not going to be a continuing concern for this project.
