### ISSUE TITLE
Unable to edit Power after creation (Tidy5e Sheet incompatibility?)

### ISSUE THREAD

**Issue by jjordalope** [JPMeehan/prime-psionics#26]
foundry 11.315 dnd5e 2.4.1 Prime psionics 1.0.3
I can create a Power Item, but there is no way to edit it :(

EDIT: after deactivation and activation of all my modules, i found the problem appears when i activate Tidy5e sheet (0.10.0) and disapears when i deactivate it.

**Comment by JPMeehan** [comment]
In Foundry, you need to manually set the default sheet for Powers to be the one provided by the module.

**Comment by jjordalope** [comment]
it worked, thank you very much
